[SplitWire]
MTU = 1380
DNSRefreshSeconds = 60

[Group "Messengers"]
Apps = Discord.exe, DiscordSystemHelper.exe, Telegram.exe
Domains = *

[Group "ChatGPT desktop"]
Apps = ChatGPT.exe
Domains = *

[Group "AI"]
Apps = chrome.exe, firefox.exe, msedge.exe, msedgewebview2.exe
Domains = chatgpt.com, *.chatgpt.com, openai.com, *.openai.com, *.auth.openai.com, auth0.openai.com, setup.auth.openai.com, oaistatic.com, *.oaistatic.com, oaiusercontent.com, *.oaiusercontent.com, oaistatsig.com, *.oaistatsig.com, *.ct.sendgrid.net, *.intercom.io, *.intercomcdn.com, js.intercomcdn.com, openaimerge.com, *.openaimerge.com, cdn.openaimerge.com, workos.com, *.workos.com, workoscdn.com, *.workoscdn.com, cdn.workos.com, forwarder.workos.com, images.workoscdn.com, setup.workos.com, workos.imgix.net, js.stripe.com, challenges.cloudflare.com, o207216.ingest.sentry.io, o33249.ingest.sentry.io, rum.browser-intake-datadoghq.com, android.chat.openai.com, ios.chat.openai.com, desktop.chat.openai.com, tcr9i.chat.openai.com, featuregates.org, *.featuregates.org, featureassets.org, statsig.com, *.statsig.com, statsigapi.net, *.statsigapi.net

[Group "YouTube"]
Apps = *
Domains = youtube.com, *.youtube.com, youtu.be, youtube-nocookie.com, *.youtube-nocookie.com, googlevideo.com, *.googlevideo.com, ytimg.com, *.ytimg.com, youtubei.googleapis.com, youtube.googleapis.com, yt3.ggpht.com, *.ggpht.com, jnn-pa.googleapis.com
